Database-setup
Patfarmurs/saints-library-api pull request #1
Opened 2023-12-13 10:40 UTC by Patfarmurs

## In this milestone I : 
>- Create database for my library
>- Add linter configuration

2023-12-15 14:15 UTC, Kwaku28 requested changes
Hello @Patfarmurs,

Great work so far with your project. I believe this is a positive start and I look forward to the final stage of the project.


## Highlights
✔️ Good Effort
✔️ Positive start

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is based on personal references. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-12-15 14:15 UTC, Kwaku28 commented on db/schema.rb
> +    t.datetime "updated_at", null: false
[OPTIONAL]

I suggest that you do away with the `authors` table and include it as a column in the `books` table. In creating a book the essential parameters will be the name and the author, so including the author in the `books` table will be easier than having a table to record authors.

2023-12-15 19:21 UTC, Patfarmurs commented on config/database.yml
> +  password: Thyshaln08
Hi @Kwaku28  thanks for the suggestion, I'll create the env file for the authentication

2023-12-16 15:19 UTC, Kwaku28 approved these changes
Hello @Patfarmurs,

Good job implementing the changes. I wish you the best in the rest of your work.

Cheers, happy coding.

2023-12-16 15:35 UTC, Patfarmurs commented
Hello @Kwaku28 , thanks a lot for your time I appreciate that.

2023-12-16 15:35 UTC, merged